version: "3.6"

services:
  mysql:
    image: mysql:5
    container_name: invoicedb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
    ports:
      - 3305:3306
    volumes:
      - ./local/db/mysql:/var/lib/mysql